#!/bin/bash
# Change port to live e.g. 8002 (via port-forwarding tp glasstty.com:8001) when ver-2.0 released.
port=25233

# Use the following command in a separate terminal window to set up a SSH tunnel
# ssh -L 8002:glasstty.com:8001 root@glasstty.com

#telstar-util login localhost:$port 1357924680 1357924680
telstar-util login localhost:$port 2222222222 1234

