#!/bin/bash
# Change port to live e.g. 8002 (via port-forwarding tp glasstty.com:8001) when ver-2.0 released.
port=25233

./login-dev
telstar-util addframes localhost:$port ./data/frames primary
telstar-util addframes localhost:$port ./data/frames